on: [push]
# on:
#   push:
#     tags:
#       - 'v*'

name: Create A Release

jobs: 
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions, you do not need to create your own token
          SHORT_SHA: ${SHORT_SHA}
        with:
          tag_name: ${SHORT_SHA}
          release_name: ${SHORT_SHA}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

